// JSON-LD (Schema.org). Restaurant-Schema ist sprachneutral und wird für beide
// Sprachen genutzt; das Hochzeits-Service-Schema gibt es auf Deutsch und Englisch.
const restaurant = "{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Restaurant\",\n  \"@id\": \"https://www.neo-heidelberg.de/#restaurant\",\n  \"name\": \"NEO Bar & Restaurant\",\n  \"image\": [\n    \"https://www.neo-heidelberg.de/img/og-image.jpg\",\n    \"https://www.neo-heidelberg.de/img/Neo_Gerichte_by_SelinaGargiullo-00546-scaled.webp\"\n  ],\n  \"logo\": \"https://www.neo-heidelberg.de/img/NEO_LOGO_white_small.webp\",\n  \"url\": \"https://www.neo-heidelberg.de/\",\n  \"telephone\": \"+4962217239099\",\n  \"email\": \"info@neo-heidelberg.de\",\n  \"priceRange\": \"€€€\",\n  \"servesCuisine\": [\"Steakhouse\", \"Sushi\", \"Dry-Aged Beef\", \"Modern European\"],\n  \"acceptsReservations\": \"https://reservation.gastronaut.ai/neo-heidelberg\",\n  \"address\": {\n    \"@type\": \"PostalAddress\",\n    \"streetAddress\": \"Zollhofgarten 2\",\n    \"addressLocality\": \"Heidelberg\",\n    \"postalCode\": \"69115\",\n    \"addressRegion\": \"Baden-Württemberg\",\n    \"addressCountry\": \"DE\"\n  },\n  \"geo\": {\n    \"@type\": \"GeoCoordinates\",\n    \"latitude\": 49.4018,\n    \"longitude\": 8.6722\n  },\n  \"openingHoursSpecification\": [\n    {\n      \"@type\": \"OpeningHoursSpecification\",\n      \"dayOfWeek\": [\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\"],\n      \"opens\": \"17:30\",\n      \"closes\": \"24:00\"\n    },\n    {\n      \"@type\": \"OpeningHoursSpecification\",\n      \"dayOfWeek\": [\"Friday\", \"Saturday\"],\n      \"opens\": \"17:30\",\n      \"closes\": \"01:00\"\n    },\n    {\n      \"@type\": \"OpeningHoursSpecification\",\n      \"dayOfWeek\": \"Sunday\",\n      \"opens\": \"16:00\",\n      \"closes\": \"23:00\"\n    }\n  ],\n  \"sameAs\": [\n    \"https://www.instagram.com/neo_bar_restaurant/\",\n    \"https://www.facebook.com/NEO.Heidelberg/\"\n  ],\n  \"hasMenu\": \"https://www.neo-heidelberg.de/img/NEO_Speisekarte_2026.pdf\",\n  \"foundingDate\": \"2016\",\n  \"slogan\": \"Feed your soul.\"\n}";

const weddingDe = "{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Service\",\n  \"serviceType\": \"Hochzeitslocation\",\n  \"provider\": {\n    \"@id\": \"https://www.neo-heidelberg.de/#restaurant\"\n  },\n  \"name\": \"Hochzeiten im NEO Heidelberg\",\n  \"description\": \"Hochzeiten im Neo Bar & Restaurant Heidelberg. Bis zu 199 Gäste. Restaurant, Bar, Terrasse und Garten. Catering, Bar und DJ komplett aus dem Haus.\",\n  \"areaServed\": {\n    \"@type\": \"City\",\n    \"name\": \"Heidelberg\"\n  }\n}";

const weddingEn = "{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Service\",\n  \"serviceType\": \"Wedding venue\",\n  \"provider\": {\n    \"@id\": \"https://www.neo-heidelberg.de/#restaurant\"\n  },\n  \"name\": \"Weddings at NEO Heidelberg\",\n  \"description\": \"Weddings at Neo Bar & Restaurant Heidelberg. Up to 199 guests. Restaurant, bar, terrace and garden. Catering, bar and DJ entirely in-house.\",\n  \"areaServed\": {\n    \"@type\": \"City\",\n    \"name\": \"Heidelberg\"\n  }\n}";

export const structuredData = [restaurant, weddingDe];
export const structuredDataEn = [restaurant, weddingEn];
